### ISSUE TITLE
Exception: Cannot open file handle for /dev/i2c-1 got -1 back.

### ISSUE THREAD

**Issue by simondid** [hsilomedus/raspi-pn532#1]
hey so i'm testing you're code with out the pn532 board Connect and im getting the following error when running the program  

pi@raspberrypi ~/NetBeansProjects/NFC/dist $ sudo java -jar NFC.jar
Starting up...
Exception: Cannot open file handle for /dev/i2c-1 got -1 back.
Exception in thread "main" java.lang.NullPointerException
        at nfc.PN532I2C.writeCommand(PN532I2C.java:97)
        at nfc.PN532I2C.writeCommand(PN532I2C.java:156)
        at nfc.PN532.getFirmwareVersion(PN532.java:28)
        at nfc.Main.main(Main.java:16)

is this becouse i don't have the board connected ore is there somthing wrong with my setup ?

**Comment by hsilomedus** [comment]
Seems like the i2c is either blacklisted or disabled.Check the instructions here: https://github.com/hsilomedus/door-nfx
Pance.

**Comment by simondid** [comment]
hmm okay tryed a few things and found out that the code was setup to i2c and i was traying to run it as spi so that solved the problem :P
